import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        serif: ["'Playfair Display'", "Georgia", "serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        brand: {
          primary: "hsl(var(--brand-primary))",
          "primary-foreground": "hsl(var(--brand-primary-foreground))",
          secondary: "hsl(var(--brand-secondary))",
          accent: "hsl(var(--brand-accent))",
          "blue-900": "hsl(var(--brand-blue-900))",
          "blue-800": "hsl(var(--brand-blue-800))",
          "blue-700": "hsl(var(--brand-blue-700))",
          "blue-600": "hsl(var(--brand-blue-600))",
          "blue-500": "hsl(var(--brand-blue-500))",
          "blue-400": "hsl(var(--brand-blue-400))",
          "blue-300": "hsl(var(--brand-blue-300))",
          "blue-200": "hsl(var(--brand-blue-200))",
          "blue-100": "hsl(var(--brand-blue-100))",
          "gold-900": "hsl(var(--brand-gold-900))",
          "gold-800": "hsl(var(--brand-gold-800))",
          "gold-700": "hsl(var(--brand-gold-700))",
          "gold-600": "hsl(var(--brand-gold-600))",
          "gold-500": "hsl(var(--brand-gold-500))",
          "gold-400": "hsl(var(--brand-gold-400))",
          "gold-300": "hsl(var(--brand-gold-300))",
          "gold-200": "hsl(var(--brand-gold-200))",
          "gold-100": "hsl(var(--brand-gold-100))",
          ivory: "hsl(var(--brand-ivory))",
          "ivory-warm": "hsl(var(--brand-ivory-warm))",
          charcoal: "hsl(var(--brand-charcoal))",
          slate: "hsl(var(--brand-slate))",
          "slate-light": "hsl(var(--brand-slate-light))",
          museum: "hsl(var(--brand-museum))",
          "museum-warm": "hsl(var(--brand-museum-warm))",
          parchment: "hsl(var(--brand-parchment))",
          "demi-blue": "hsl(var(--brand-demi-blue))",
          "demi-blue-light": "hsl(var(--brand-demi-blue-light))",
          "demi-blue-dark": "hsl(var(--brand-demi-blue-dark))",
          "gray-blue": "hsl(var(--brand-gray-blue))",
          "gray-blue-deep": "hsl(var(--brand-gray-blue-deep))",
          "gray-blue-deeper": "hsl(var(--brand-gray-blue-deeper))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-down": {
          "0%": { opacity: "0", transform: "translateY(-100%)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "submenu-enter": {
          "0%": { opacity: "0", transform: "translateY(-20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        "slide-down": "slide-down 0.3s ease-out",
        "submenu-enter": "submenu-enter 0.5s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
